FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY Irrigation_api.py

CMD ["uvicorn","Irrigation_api:app","--host", "0.0.0.0","--port","8000"]


